Repository dongwu-kim/soomgo_wecode_commuting_app, pull requests merged in 2021-09, with the labels that each got.

#13 [Steve] [ADD]구글 소셜 로그인 로직 추가
  app/model/useCase/signInSocialAuth.tsx
  app/view/SignIn.tsx
Labels: Status : Fix 완료

#14 [Hugo] [ADD] : SignInValidation logic 작성
  Navigation.tsx
  app/data/repository/SignInRepository.ts
  app/data/repository/UsingFirebaseDB.ts
  app/domain/useCase/SignInUseCase.ts
  app/model/repository/databaseMethod.ts
  app/model/useCase/signInSocialAuth.tsx
  app/model/useCase/useDB.ts
  app/presentation/components/signIn/SignIn.tsx
  app/presentation/components/signIn/SignInPresenter.tsx
  app/presentation/hooks/signIn.ts
  app/presentation/interface/ISignIn.ts
  ios/Podfile.lock
  ios/soomgo_wecode_commute_app.xcodeproj/project.pbxproj
  ios/soomgo_wecode_commute_app/AppDelegate.m
Labels: Status : Review 요청

#15 [Hugo&Milo] [ADD] : Main Layout & Firebase DB 연동 (android fix)
  Navigation.tsx
  android/app/google-services.json
  app/presentation/components/main/Main.tsx
Labels: Status : Review 요청

#16 [Hugo] [ADD] : WorkLog layout && dayjs logic && WorkLog Load data logic
  Navigation.tsx
  app/data/repository/SignInRepository.ts
  app/data/repository/WorkLogRepository.ts
  app/domain/useCase/WorkLogUseCase.ts
  app/presentation/components/main/Main.tsx
  app/presentation/components/workLog/WorkLog.tsx
  app/presentation/components/workLog/WorkLogPresenter.tsx
  app/presentation/hooks/worklog.ts
  app/presentation/interface/IWorkLog.ts
  app/utils/dayjs.ts
  package-lock.json
  package.json
Labels: Status : Review 요청

#17 [Hugo] [MODIFY] : WorkLog Load logic & SaveOrInsert button toggle
  .prettierrc.js
  app/data/repository/WorkLogRepository.ts
  app/domain/useCase/WorkLogUseCase.ts
  app/presentation/components/workLog/WorkLog.tsx
  app/presentation/components/workLog/WorkLogPresenter.tsx
  app/presentation/interface/IWorkLog.ts
  app/utils/dayjs.ts
Labels: Status : Review 요청

#18 [Hugo] [SETTING] : arm64 excluded && [MODIFY] : Main component navigation 수정
  Navigation.tsx
  app/presentation/components/main/Main.tsx
  app/presentation/components/main/MainPresenter.tsx
Labels: Status : Review 요청

#21 [Milo] [MODIFY] Main WorkTime ToggleButton Presenter
  app/data/repository/MainWorkThisWeekRepository.ts
  app/presentation/components/main/Main.tsx
  app/presentation/components/main/MainPresenter.tsx
  app/presentation/interface/IWorkThisWeek.ts
  app/presentation/interface/IWorkTime.ts
  app/utils/dayjs.ts
  ios/soomgo_wecode_commute_app.xcodeproj/project.pbxproj
  ios/soomgo_wecode_commute_app.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Labels: Status : Review 요청

#22 [ADD] : 출퇴근 toggle & [MODIFY] : DB 구조 전면 수정
  app/data/repository/MainWorkThisWeekRepository.ts
  app/data/repository/UsingFirebaseDB.ts
  app/data/repository/main/MainRepository.ts
  app/data/repository/signIn/SignInRepository.ts
  app/data/repository/workLog/WorkLogRepository.ts
  app/presentation/components/main/Main.tsx
  app/presentation/components/main/MainPresenter.tsx
  app/presentation/components/signIn/SignInPresenter.tsx
  app/presentation/hooks/useTodayWorkTimeLog.ts
  app/presentation/interface/IMainProps.ts
  app/presentation/interface/IWorkThisWeek.ts
  app/presentation/interface/IWorkToday.ts
  app/utils/dayjs.ts
Labels: Status : Review 요청

#23 [ADD] : Weekly CommuteData load logic
  app/data/repository/main/MainRepository.ts
  app/presentation/components/main/MainPresenter.tsx
  app/presentation/hooks/useTodayWorkTimeLog.ts
  app/presentation/hooks/useWeeklyWorkTime.ts
  app/presentation/interface/IWeeklyWorkLog.ts
  app/utils/dayjs.ts
  data/json/holiday.json
Labels: Status : Review 요청

#24 [Hugo] [ADD] Week workTime & progress bar logic & holiday.json
  app/data/repository/main/MainRepository.ts
  app/domain/useCase/main/MainUseCase.ts
  app/domain/useCase/main/MainWorkThisWeekUseCase.ts
  app/presentation/components/main/Main.tsx
  app/presentation/components/main/MainPresenter.tsx
  app/presentation/components/main/MainWorkThisWeek.tsx
  app/presentation/hooks/useWeeklyWorkTime.ts
  app/presentation/interface/IMainProps.ts
  app/presentation/interface/IWeeklyWorkLog.ts
  app/utils/dayjs.ts
Labels: Status : Review 요청

#25 [Steve][MODIFY] 지오로케이션 위치정보획득 로직 변경
  app/presentation/hooks/useLocation.ts
Labels: Status : Review 요청

#26 [Hugo] [FIX] : weekWorkTime Logic & [ADD] : userName & dailyWorkTime logic
  app/data/repository/main/MainRepository.ts
  app/presentation/components/main/Main.tsx
  app/presentation/components/main/MainPresenter.tsx
  app/presentation/components/signIn/SignInPresenter.tsx
  app/presentation/hooks/useTodayWorkTimeLog.ts
  app/presentation/hooks/useUserName.ts
  app/presentation/hooks/useWeeklyWorkTime.ts
  app/presentation/interface/IMainProps.ts
  app/utils/dayjs.ts
Labels: Status : Review 요청

#27 [Hugo & Steve] [ADD] : thisWeek workTime mapping & ACCESS_FINE_LOCATION
  android/app/src/main/AndroidManifest.xml
  app/presentation/components/main/Main.tsx
  app/presentation/components/main/MainPresenter.tsx
  app/presentation/components/main/MainWorkThisWeek.tsx
  app/presentation/hooks/useUserName.ts
  app/presentation/hooks/useWeeklyWorkTime.ts
  app/presentation/interface/IMainProps.ts
  app/utils/dayjs.ts
Labels: Status : merge

#28 [Hugo] [ADD] : businessDay logic
  app/data/repository/main/MainRepository.ts
  app/domain/useCase/main/MainUseCase.ts
  app/presentation/components/main/Main.tsx
  app/presentation/components/main/MainPresenter.tsx
  app/presentation/interface/IMainProps.ts
Labels: Status : merge

#29 [Hugo] [FIX] : thisWeekWorkTime logic fix
  app/data/repository/main/MainRepository.ts
  app/presentation/components/main/Main.tsx
  app/presentation/components/main/MainPresenter.tsx
  app/presentation/hooks/useThisWeekWorkTime.ts
  app/utils/dayjs.ts
Labels: Status : Review 요청

#30 [Hugo] [FIX] : thisWeekWorkTime logic fix 2
  app/presentation/components/main/MainWorkThisWeek.tsx
Labels: Status : Review 요청

#32 [Milo] [ADD] Feature/tab navigator
  Navigation.tsx
  app/presentation/components/meeting/Meeting.tsx
  app/presentation/components/myPage/MyPage.tsx
  package-lock.json
  package.json
Labels: Status : Review 요청

#33 [Hugo] [ADD] : weeklyWorkTime & calendar logic
  Navigation.tsx
  app/data/repository/main/MainRepository.ts
  app/domain/useCase/main/MainUseCase.ts
  app/presentation/components/DatePicker/DatePicker.tsx
  app/presentation/components/main/Main.tsx
  app/presentation/components/main/MainPresenter.tsx
  app/presentation/hooks/useWorkTimeAverage.ts
  app/presentation/interface/IMainProps.ts
  app/utils/dayjs.ts
  package-lock.json
  package.json
Labels: Status : Review 요청

#31 [Steve] [ADD] Feature/woktime detail
  Navigation.tsx
  app/presentation/components/main/Main.tsx
  app/presentation/components/worktimedetail/WorkTimeDetail.tsx
  package-lock.json
Labels: Status : Review 요청

#34 [ADD] : workTimeDetailLog logic
  Navigation.tsx
  app/data/repository/workTimeDetail/WorkTimeDetailRepository.ts
  app/domain/useCase/workTimeDetail/WorkTimeDetailUseCase.ts
  app/presentation/components/worktimedetail/WorkTimeDetail.tsx
  app/presentation/components/worktimedetail/WorkTimeDetailPresenter.tsx
  app/presentation/hooks/useWorkTimeDetailLog.ts
  app/presentation/interface/IWorkTimeDetailProps.ts
  app/presentation/interface/IWorkTimeInfo.ts
Labels: Status : Review 요청

#36 [Hugo] [FIX] : thisWeek / logDetail Layout && workTime Logic
  app/data/repository/main/MainRepository.ts
  app/domain/useCase/main/MainUseCase.ts
  app/presentation/components/main/Main.tsx
  app/presentation/components/main/MainPresenter.tsx
  app/presentation/components/main/MainWorkThisWeek.tsx
  app/presentation/components/worktimedetail/WorkTimeDetail.tsx
  app/presentation/hooks/useThisWeekWorkTime.ts
  app/presentation/interface/IDailyWorkLog.ts
  app/presentation/interface/IMainProps.ts
  app/presentation/interface/IWeeklyWorkLog.ts
  app/utils/dayjs.ts
Labels: Status : Review 요청

#37 [Hugo] [MODIFY] : calendar Layout
  app/presentation/components/DatePicker/DatePicker.tsx
Labels: Status : Review 요청

#38 [Hugo] [MODIFY] : Task Layout
  app/presentation/components/workLog/WorkLog.tsx
Labels: Status : Review 요청

#39 [Milo] [MODIFY] : Feature/fix layout
  Navigation.tsx
  app/presentation/components/main/Main.tsx
  app/presentation/components/main/MainWorkThisWeek.tsx
  data/images/home.png
  data/images/meeting.png
  data/images/myPage.png
Labels: Status : Review 요청

#42 [Hugo] [FIX] : safeAreaView fix
  Navigation.tsx
  app/presentation/components/main/Main.tsx
  app/presentation/components/main/MainWorkThisWeek.tsx
  app/presentation/components/workLog/WorkLog.tsx
  ios/soomgo_wecode_commute_app/AppDelegate.m
Labels: Status : Review 요청

#43 [Milo] [MODIFY] : meeting,mypage ComingSoon
  Navigation.tsx
  app/presentation/components/main/Main.tsx
  app/presentation/components/meeting/Meeting.tsx
  app/presentation/components/myPage/MyPage.tsx
  data/images/myPage.png
Labels: Status : merge

#44 [MODIFY] : TimeStamp 기준 변경, Maps 위치정보 전달, 출퇴근 toggle, 이번주 근무 공휴일 제외 등
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  app/data/repository/UsingFirebaseDB.ts
  app/data/repository/main/MainRepository.ts
  app/domain/useCase/main/MainUseCase.ts
  app/presentation/components/DatePicker/DatePicker.tsx
  app/presentation/components/main/Main.tsx
  app/presentation/components/main/MainPresenter.tsx
  app/presentation/components/main/MainWorkThisWeek.tsx
  app/presentation/components/map/Maps.tsx
  app/presentation/hooks/useLocation.ts
  app/presentation/hooks/useWorkTimeAverage.ts
  app/presentation/interface/IMainProps.ts
  app/presentation/interface/IMapLocation.ts
Labels: Status : Review 요청

#45 [Hugo] [MODIFY] : 일평균 근로시간 logic 수정 & 근무예정 margin 추가 & 근무일지 지난주 일과 불러오기 추가
  app/data/repository/main/MainRepository.ts
  app/data/repository/workLog/WorkLogRepository.ts
  app/domain/useCase/workLog/WorkLogUseCase.ts
  app/presentation/components/main/MainPresenter.tsx
  app/presentation/components/main/MainWorkThisWeek.tsx
  app/presentation/hooks/useWorkTimeAverage.ts
Labels: Status : Review 요청

#46 [MODIFY] : load dayAvg workTime && detailLog logic
  app/data/repository/main/MainRepository.ts
  app/data/repository/workTimeDetail/WorkTimeDetailRepository.ts
Labels: Status : Review 요청

#47 [Hugo] [ADD] : 발표용 view 제작
  app/presentation/components/meeting/Meeting.tsx
  app/presentation/components/myPage/MyPage.tsx
Labels: Status : Review 요청

#55 [ADD] : WokrTimeDetailRepository test logic
  app/data/repository/main/MainRepository.ts
  app/data/repository/workTimeDetail/WorkTimeDetailRepo.test.ts
  app/data/repository/workTimeDetail/WorkTimeDetailRepository.ts
  app/domain/useCase/main/MainUseCase.ts
  app/utils/dayjs.test.ts
  app/utils/dayjs.ts
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/dayjs.ts.html
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov.info
  jest.config.js
  package-lock.json
  package.json
Labels: Status : Review 요청

#57 [ADD] : UsingFirebaseDB test logic
  app/data/repository/UsingFirebaseDB.test.ts
  app/data/repository/workLog/WorkLogRepository.test.ts
  app/data/repository/workTimeDetail/WorkTimeDetailRepo.test.ts
  jest.config.js
Labels: Status : Review 요청

#58 [ADD] : SignInRepository test logic
  app/data/repository/signIn/SignInRepository.test.ts
  app/data/repository/workLog/WorkLogRepository.test.ts
Labels: Status : Review 요청
